project_id = "vjwsflqtvcbvsbwabcfe"

[auth]
site_url = "https://test.liefdevolleblik.nl/matchmaker"
additional_redirect_urls = [
  "https://test.liefdevolleblik.nl/matchmaker/auth/callback",
  "http://localhost:3000/auth/callback"
]

[auth.email]
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
